### ISSUE TITLE
pytorch/master CUDA OOM for kdd appetency w/automl; same config seems to train okay on tensorflow/tf-legacy

### ISSUE THREAD

**Issue by amholler** [ludwig-ai/ludwig#1705]
The trial that fails has this configuration, which seems to train okay on tensorflow on the same size worker:
```
| Trial name     | status     | loc                 |   combiner.bn_momentum |   combiner.bn_virtual_bs |   combiner.num_steps |   combiner.output_size |   combiner.relaxation_factor |   combiner.size |   combiner.sparsity |   training.batch_size |   training.decay_rate |   training.decay_steps |   training.learning_rate |   iter |   total time (s) |   metric_score |

| trial_e6687d84 | ERROR      | 172.31.10.68:26084  |                   0.7  |                     2048 |                    4 |                      8 |                          1   |              32 |              0.0001 |                  8192 |                  0.95 |                    500 |                    0.025 |        |                  |                |
```

**Comment by amholler** [comment]
The stack dump is:
```
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m 2022-01-23 08:17:12,441       ERROR function_runner.py:268 -- Runner Thread raised error.
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m Traceback (most recent call last):
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 262, in run
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     self._entrypoint()
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     self._status_reporter.get_checkpoint())
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return method(self, *_args, **_kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     output = fn()
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/trainable.py", line 344, in inner
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     trainable(config, **fn_kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/hyperopt/execution.py", line 699, in run_experiment_trial
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     config, checkpoint_dir, local_hyperopt_dict, self.decode_ctx, _is_ray_backend(backend)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/hyperopt/execution.py", line 568, in _run_experiment
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     _run()
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/hyperopt/execution.py", line 535, in _run
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     parameters=config,
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/hyperopt/execution.py", line 920, in run_experiment
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     debug=debug,
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/api.py", line 1078, in experiment
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     debug=debug,
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/api.py", line 538, in train
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     save_path=model_dir,
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/models/trainer.py", line 741, in train
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     self._train_loop(batcher, progress_tracker, save_path, train_summary_writer, progress_bar)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/models/trainer.py", line 931, in _train_loop
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     targets,
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/models/trainer.py", line 307, in train_step
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     model_outputs = self.model((inputs, targets))
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return forward_call(*input, **kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/models/ecd.py", line 141, in forward
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     combiner_outputs = self.combiner(encoder_outputs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return forward_call(*input, **kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/combiners/combiners.py", line 491, in forward
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     hidden, aggregated_mask, masks = self.tabnet(hidden)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return forward_call(*input, **kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/modules/tabnet_modules.py", line 118, in forward
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     mask_values = self.attentive_transforms[step_i](x[:, self.output_size :], prior_scales)  # [b_s, i_s]
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return forward_call(*input, **kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/modules/tabnet_modules.py", line 252, in forward
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return self.sparsemax(hidden)  # [b_s, s]
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return forward_call(*input, **kwargs)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/utils/torch_utils.py", line 305, in forward
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     return sparsemax(input, self.dim)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/utils/torch_utils.py", line 252, in forward
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     tau, supp_size = SparsemaxFunction._threshold_and_support(input, dim=dim)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m   File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/utils/torch_utils.py", line 285, in _threshold_and_support
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m     input_srt, _ = torch.sort(input, descending=True, dim=dim)
^[[2m^[[36m(ImplicitFunc pid=26034, ip=172.31.10.68)^[[0m RuntimeError: CUDA out of memory. Tried to allocate 322.00 MiB (GPU 0; 14.76 GiB total capacity; 13.30 GiB already allocated; 119.75 MiB free; 13.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by amholler** [comment]
Note that kdd requires fix to load on master and tf-legacy; PRs are available.

**Comment by amholler** [comment]
The problem can be reproduced by running
https://github.com/ludwig-ai/experiments/blob/main/automl/validation/kdd/run_auto_train_1hr.py

**Comment by amholler** [comment]
Running on g4dn.4xlarge https://aws.amazon.com/ec2/instance-types/g4/

**Comment by justinxzhao** [comment]
I'm able to reproduce the OOM on Torch with the highlighted parameters, which uses a batch size of 8192.

However, I get the same OOM error on Tensorflow.

I tried a few different batch sizes on both Torch and Tensorflow on ray, using `nvidia-smi` to monitor memory usage.

Overall we see that at each batch size, Torch uses a bit more memory than Tensorflow. 4096 is already quite close to the memory max of 15k MiB memory limit for both branches, so it's not surprising that 8192 is too large for either branch. 
![image](https://user-images.githubusercontent.com/3459541/152893318-f8ec0451-99b8-44e4-918d-6913557cff2f.png)

@anneholler I'm curious if you're able to reproduce this finding on your end. If the OOM isn't unique to torch, then I think we can close the issue.

**Comment by amholler** [comment]
```
Hi, Justin,

Thanks for looking at the problem and for producing the interesting memory use graphs.

Unfortunately, I can still reproduce the problem.
  
To aid repro, I've created a 5min run (ignore the "1hr" in script name) that can be executed on a single node [head-only]
Ray gpu-enabled cluster [g4dn.4xlarge], in which the troublesome config is passed as an initial point to evaluate.
 This script passes on the tf-legacy branch:
  https://github.com/ludwig-ai/experiments/blob/main/automl/validation/kdd/run_auto_train_1hr_repro_tf.py
 This comparable script fails on the master branch:
  https://github.com/ludwig-ai/experiments/blob/main/automl/validation/kdd/run_auto_train_1hr_repro_master.py

One thought is that the problem could be associated with the datatypes inferred for the input features,
which are quite a bit different between master and tf-legacy.
 Latest automl config produced by Master:
  https://github.com/ludwig-ai/experiments/blob/main/automl/validation/kdd/auto_config.json.automl.appetency.master
 Latest automl config produced by tf-legacy:
  https://github.com/ludwig-ai/experiments/blob/main/automl/validation/kdd/auto_config.json.automl.appetency.tf

I'm thinking that in your repro work yesterday, you may have used the master inferred datatypes in your tf-legacy run,
and if the datatypes are the problem, that could be what made your tf-legacy runs fail.
```

**Comment by justinxzhao** [comment]
Thanks for supplying the repro scripts! Definitely very useful for drilling into this more deeply.

Indeed, for my runs, I was using the same explicitly specified types for both master and tf-legacy, rather than relying on each branch's automatically inferred types.

It appears that indeed the type assignment differences are the culprit. Master assigns the `text` type to many more columns than `tf-legacy` does, probably related to [this change](https://github.com/ludwig-ai/ludwig/pull/1542). Here's a sampling:

`master`:
```
{'column': 'Var191', 'name': 'Var191', 'type': 'category'},
                    {'column': 'Var192', 'name': 'Var192', 'type': 'text'},
                    {'column': 'Var193', 'name': 'Var193', 'type': 'text'},
                    {'column': 'Var194', 'name': 'Var194', 'type': 'category'},
                    {'column': 'Var195', 'name': 'Var195', 'type': 'text'},
                    {'column': 'Var196', 'name': 'Var196', 'type': 'category'},
                    {'column': 'Var197', 'name': 'Var197', 'type': 'text'},
                    {'column': 'Var198', 'name': 'Var198', 'type': 'text'},
                    {'column': 'Var199', 'name': 'Var199', 'type': 'text'},
                    {'column': 'Var200', 'name': 'Var200', 'type': 'text'},
                    {'column': 'Var201', 'name': 'Var201', 'type': 'category'},
                    {'column': 'Var202', 'name': 'Var202', 'type': 'text'},
                    {'column': 'Var203', 'name': 'Var203', 'type': 'category'},
                    {'column': 'Var204', 'name': 'Var204', 'type': 'text'},
                    {'column': 'Var205', 'name': 'Var205', 'type': 'category'},
                    {'column': 'Var206', 'name': 'Var206', 'type': 'text'},
                    {'column': 'Var207', 'name': 'Var207', 'type': 'category'},
                    {'column': 'Var208', 'name': 'Var208', 'type': 'category'},
                    {'column': 'Var210', 'name': 'Var210', 'type': 'category'},
                    {'column': 'Var211', 'name': 'Var211', 'type': 'category'},
                    {'column': 'Var212', 'name': 'Var212', 'type': 'text'},
                    {'column': 'Var213', 'name': 'Var213', 'type': 'category'},
                    {'column': 'Var214', 'name': 'Var214', 'type': 'text'},
                    {'column': 'Var215', 'name': 'Var215', 'type': 'category'},
                    {'column': 'Var216', 'name': 'Var216', 'type': 'text'},
                    {'column': 'Var217', 'name': 'Var217', 'type': 'text'},
                    {'column': 'Var218', 'name': 'Var218', 'type': 'category'},
                    {'column': 'Var219', 'name': 'Var219', 'type': 'text'},
                    {'column': 'Var220', 'name': 'Var220', 'type': 'text'},
                    {'column': 'Var221', 'name': 'Var221', 'type': 'category'},
                    {'column': 'Var222', 'name': 'Var222', 'type': 'text'},
                    {'column': 'Var223', 'name': 'Var223', 'type': 'category'},
                    {'column': 'Var224', 'name': 'Var224', 'type': 'category'},
                    {'column': 'Var225', 'name': 'Var225', 'type': 'category'},
                    {'column': 'Var226', 'name': 'Var226', 'type': 'text'},
                    {'column': 'Var227', 'name': 'Var227', 'type': 'category'},
                    {'column': 'Var228', 'name': 'Var228', 'type': 'text'},
                    {'column': 'Var229', 'name': 'Var229', 'type': 'category'}
```

vs. `tf-legacy`

```
{'column': 'Var191', 'name': 'Var191', 'type': 'category'},
                    {'column': 'Var192', 'name': 'Var192', 'type': 'category'},
                    {'column': 'Var193', 'name': 'Var193', 'type': 'category'},
                    {'column': 'Var194', 'name': 'Var194', 'type': 'category'},
                    {'column': 'Var195', 'name': 'Var195', 'type': 'category'},
                    {'column': 'Var196', 'name': 'Var196', 'type': 'category'},
                    {'column': 'Var197', 'name': 'Var197', 'type': 'category'},
                    {'column': 'Var198', 'name': 'Var198', 'type': 'category'},
                    {'column': 'Var199', 'name': 'Var199', 'type': 'category'},
                    {'column': 'Var200', 'name': 'Var200', 'type': 'category'},
                    {'column': 'Var201', 'name': 'Var201', 'type': 'category'},
                    {'column': 'Var202', 'name': 'Var202', 'type': 'category'},
                    {'column': 'Var203', 'name': 'Var203', 'type': 'category'},
                    {'column': 'Var204', 'name': 'Var204', 'type': 'category'},
                    {'column': 'Var205', 'name': 'Var205', 'type': 'category'},
                    {'column': 'Var206', 'name': 'Var206', 'type': 'category'},
                    {'column': 'Var207', 'name': 'Var207', 'type': 'category'},
                    {'column': 'Var208', 'name': 'Var208', 'type': 'category'},
                    {'column': 'Var209', 'name': 'Var209', 'type': 'numerical'},
                    {'column': 'Var210', 'name': 'Var210', 'type': 'category'},
                    {'column': 'Var211', 'name': 'Var211', 'type': 'category'},
                    {'column': 'Var212', 'name': 'Var212', 'type': 'category'},
                    {'column': 'Var213', 'name': 'Var213', 'type': 'category'},
                    {'column': 'Var214', 'name': 'Var214', 'type': 'category'},
                    {'column': 'Var215', 'name': 'Var215', 'type': 'category'},
                    {'column': 'Var216', 'name': 'Var216', 'type': 'category'},
                    {'column': 'Var217', 'name': 'Var217', 'type': 'category'},
                    {'column': 'Var218', 'name': 'Var218', 'type': 'category'},
                    {'column': 'Var219', 'name': 'Var219', 'type': 'category'},
                    {'column': 'Var220', 'name': 'Var220', 'type': 'category'},
                    {'column': 'Var221', 'name': 'Var221', 'type': 'category'},
                    {'column': 'Var222', 'name': 'Var222', 'type': 'category'},
                    {'column': 'Var223', 'name': 'Var223', 'type': 'category'},
                    {'column': 'Var224', 'name': 'Var224', 'type': 'category'},
                    {'column': 'Var225', 'name': 'Var225', 'type': 'category'},
                    {'column': 'Var226', 'name': 'Var226', 'type': 'category'},
                    {'column': 'Var227', 'name': 'Var227', 'type': 'category'},
                    {'column': 'Var228', 'name': 'Var228', 'type': 'category'},
                    {'column': 'Var229', 'name': 'Var229', 'type': 'category'},
```

The default encoder for text features is a `parallel_cnn`, which is significantly heavier than the default single dense layer encoder for category features. It's not surprising that the config with many more text features runs into OOM (on both branches). Additionally, when I use `tf-legacy`'s column typing for `torch`, then torch no longer gets the OOM error. :)

This issue is now resolved in the sense that we see the same OOM / non-OOM behavior across both branches with the exact same config, just that the branches assign different types.

It's still an open question about whether we should fix the type assignment, and/or downgrade the text feature's default encoder to something a bit less intense, like `embed`, which might be good to do anyways.

**Comment by amholler** [comment]
https://github.com/ludwig-ai/ludwig/pull/1755
